### ISSUE TITLE
Knotenzahl aktualisieren

### ISSUE THREAD

**Issue by nazco** [Freifunk-Rhein-Neckar/oeffentlichkeitsarbeit#11]
Im Anschreiben an Nachbarn steht noch das wir 500 Knoten haben. Da wir inzwischen aber über 600 Stück haben, könnten wir das aktualisieren.

**Comment by nazco** [comment]
Bitte dann übrigens max. als CS6 da @Cheatha es sonst nicht mehr öffnen kann. Danke :)

**Comment by marteb** [comment]
Hab ich angepasst und zur InDesign CS4+ Kompatibilität jeweils als .idml gespeichert. InDesign CC kann leider keine .indd mehr für CS6 speichern :-/
