### ISSUE TITLE
wording "propaganda"

### ISSUE THREAD

**Issue by Myonit** [Freifunk-Rhein-Neckar/oeffentlichkeitsarbeit#4]
Das Wort Propaganda ist negativ konnotiert. Dazu Wikipedia: 

"Propaganda (von lateinisch propagare ‚weiter ausbreiten, ausbreiten, verbreiten‘) bezeichnet einen absichtlichen und systematischen Versuch, öffentliche Sichtweisen zu formen, Erkenntnisse zu manipulieren und Verhalten zum Zwecke der Erzeugung einer vom Propagandisten oder Herrscher erwünschten Reaktion zu steuern."

Deshalb sollte es nicht in Links enthalten sein, die öffentlich kommuniziert werden. Stattdessen sollte das Wort "promotion" oder "promo" verwendet werden.

**Comment by HDValentin** [comment]
@Myonit danke für den Hinweis
@silsha könntest Du dies im Git bitte ändern. Das Projekt könnte "Öffentlichkeitsarbeit" heißen oder "Materialien"
